name: Compile Documentation to Markdown

on:
  push:
    branches:
      - json_sample

jobs:
  compile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Copy schema
        run: cp ./schema/iea43_wra_data_model_schema.json ./app/src/schema.json

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install jsonschema2md
        run: npm install -g @adobe/jsonschema2md

      - name: Compile docs to Markdown
        run: jsonschema2md -d schema -o docs

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "Compile documentation"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}